### PR TITLE
added class variable mounts

### PR DESCRIPTION
**Pull request by slot**
I wanted to use this module in Foreman and for that I needed a class variable mounts, which I now added to your package.

### CODE REVIEW

**Comment by chrisjohnson1988** [comment]
I don't have any problem with this. However I think if we take this approach enable the init.pp to `create_resources` for mounts, then it should also to the same for `fstab::exports`.

What do you think?

**Comment by chrisjohnson1988** [comment]
Just had another thought. Since you are defining an empty hash as the default, do we need the if statement?

**Comment by slot** [comment]
Hey Chris,

I added the same for exports now.

I would keep the if statement though. The current implementation of create_resources will work with an empty hash but you never know if t will changed in the future. The additional if won't hurt anyone. 

Let me know your thoughts. 

Sven

**Comment by chrisjohnson1988** [comment]
Looks good to me. Pretty sure I have seen others doing this check and as you say, it doesn't do any harm.

**Pull request merged**
